### PR TITLE
Fixed docker hanging when run with `--cpus 1`

### LINKED ISSUE #1763: Investigate hangup when starting in docker container with less than 2 cpu cores

### PR DESCRIPTION
**Pull request by JBRS307**
Closes #1763

### CODE REVIEW

File: src/server.rs [hunk 1]
```diff
@@ -15,7 +15,33 @@ pub fn run() {
     init_logger(config.logger.clone());
 
     info!("Starting Smelter with config:\n{:#?}", config);
-    let runtime = Arc::new(Runtime::new().unwrap());
+    let runtime = Arc::new({
```
Comment (wkozyra95) [inline src/server.rs]: logic is fine, but refactor it, at least move that to function e.g. init_runtime

File: src/server.rs [hunk 2]
```diff
@@ -15,7 +15,33 @@ pub fn run() {
...
+        const MINIMUM_WORKER_THREADS: usize = 3;
+        let available_threads = thread::available_parallelism()
+            .map(|val| val.get())
+            .unwrap_or(MINIMUM_WORKER_THREADS);
+        if available_threads >= MINIMUM_WORKER_THREADS {
+            debug!(
+                api_worker_threads = available_threads,
+                "Number of worker threads used for API."
```
Comment (wkozyra95) [inline src/server.rs]: This is not only for API, Webrtc is using that too

File: src/server.rs [hunk 3]
```diff
@@ -15,7 +15,33 @@ pub fn run() {
...
+            );
+            Runtime::new().unwrap()
+        } else {
+            let threads = env::var("TOKIO_WORKER_THREADS")
```
Comment (wkozyra95) [inline src/server.rs]:
```suggestion
            let thread_count = env::var("TOKIO_WORKER_THREADS")
```

File: src/server.rs [hunk 4]
```diff
@@ -15,7 +15,33 @@ pub fn run() {
...
+                .ok()
+                .and_then(|v| v.trim().parse().ok())
+                .unwrap_or(MINIMUM_WORKER_THREADS);
+            debug!(
+                api_worker_threads = threads,
+                "Number of worker threads used for API."
```
Comment (wkozyra95) [inline src/server.rs]: the same as above

File: src/server.rs [hunk 5]
```diff
@@ -15,7 +15,33 @@ pub fn run() {
...
+        const MINIMUM_WORKER_THREADS: usize = 3;
+        let available_threads = thread::available_parallelism()
+            .map(|val| val.get())
+            .unwrap_or(MINIMUM_WORKER_THREADS);
+        if available_threads >= MINIMUM_WORKER_THREADS {
+            debug!(
+                api_worker_threads = available_threads,
+                "Number of worker threads used for API."
+            );
+            Runtime::new().unwrap()
```
Comment (wkozyra95) [inline src/server.rs]: up to you, but in general, I would avoid different initialization modes, less risk for unexpected changes. Check what `Builder::new_multi_thread()` does by default and replicate the behavior explictlly

Comment (wkozyra95) [reply src/server.rs]: I know that i said it's up to you, but the new approach does not make sense, you are creating the builder, run some methods twice, it's still might be a different behavior dependint on which if/else branch is selected

Comment (JBRS307) [reply src/server.rs]: I think I misunderstood the first time. I'll do it with one `Builder`.

File: src/server.rs [hunk 6]
```diff
@@ -69,6 +69,37 @@ pub fn run_api(
     })
 }
 
+fn init_runtime() -> Runtime {
+    const MINIMUM_WORKER_THREADS: usize = 3;
+    let mut runtime_builder = Builder::new_multi_thread();
+    runtime_builder.enable_all();
```
Comment (noituri) [inline src/server.rs]:
```suggestion
    let mut runtime_builder = Builder::new_multi_thread().enable_all();
```

File: src/server.rs [hunk 7]
```diff
@@ -69,6 +69,37 @@ pub fn run_api(
...
+            .and_then(|v| v.trim().parse().ok())
+            .unwrap_or(MINIMUM_WORKER_THREADS);
+        debug!(
+            worker_threads = thread_count,
+            "Number of runtime worker threads used."
+        );
+        runtime_builder
+            .enable_all()
+            .worker_threads(thread_count)
+            .build()
```
Comment (noituri) [inline src/server.rs]:
```suggestion
        runtime_builder
            .worker_threads(thread_count)
            .build()
```

**Review by noituri — COMMENTED** [review]
NIT:

I think tokio will set worker threads to `std::thread::available_parallelism()` unless they are explicitly provided. So you could calculate the correct `thread_count` and then build the runtime, instead of branching on `available_threads >= MINIMUM_WORKER_THREADS`

e.g.
```rust
let available_threads = thread::available_parallelism()
   .map(|val| val.get())
   .unwrap_or(MINIMUM_WORKER_THREADS)
   .max(MINIMUM_WORKER_THREADS);
let thread_count = env::var("TOKIO_WORKER_THREADS")
   .ok()
   .and_then(|v| v.trim().parse().ok())
   .unwrap_or(available_threads);

// build runtime ....
```

File: src/server.rs [hunk 8]
```diff
@@ -69,6 +69,40 @@ pub fn run_api(
...
+        .ok()
+        .map(|v| {
+            let val: usize = v
+                .parse()
+                .expect("Failed to parse TOKIO_WORKER_THREADS. Must be a number greater than 0.");
+            if val == 0 {
+                panic!("TOKIO_WORKER_THREADS must be greater than 0.");
+            } else {
+                val
+            }
```
Comment (noituri) [inline src/server.rs]: i think this `else` is not necessary

Comment (JBRS307) [reply src/server.rs]: I think that function used inside of `Option::map()` needs to return the final value, [spec](https://doc.rust-lang.org/std/option/enum.Option.html#method.map)

File: src/server.rs [hunk 9]
```diff
@@ -69,6 +69,40 @@ pub fn run_api(
     })
 }
 
+fn init_runtime() -> Runtime {
+    const MINIMUM_WORKER_THREADS: usize = 3;
+
+    let available_threads = thread::available_parallelism().ok().map(|v| v.get());
+    trace!(available_parallelism=?available_threads, "Available cpus detected.");
```
Comment (wkozyra95) [inline src/server.rs]:
```suggestion
    trace!(?available_threads, "Available CPUs detected.");
```
or change name of the variable

File: src/server.rs (hunk 8 above)
Comment (wkozyra95) [inline src/server.rs]:
```suggestion
            match val {
                0 => panic!("TOKIO_WORKER_THREADS must be greater than 0."),
                val => val,
            }
```

File: src/server.rs [hunk 10]
```diff
@@ -69,6 +69,40 @@ pub fn run_api(
...
+    let available_threads = available_threads
+        .unwrap_or(MINIMUM_WORKER_THREADS)
+        .max(MINIMUM_WORKER_THREADS);
+
+    let thread_count = env::var("TOKIO_WORKER_THREADS")
+        .ok()
```
Comment (wkozyra95) [inline src/server.rs]: what is this ok() here?

File: src/server.rs [hunk 11]
```diff
@@ -69,6 +69,40 @@ pub fn run_api(
...
+            } else {
+                val
+            }
+        })
+        .unwrap_or(available_threads);
+
+    debug!(
+        worker_threads = thread_count,
+        "Number of runtime worker threads."
+    );
```
Comment (wkozyra95) [inline src/server.rs]:
```suggestion
    debug!(thread_count, "Number of runtime worker threads.");
```
