### PR TITLE
Fixed blinking when static tile is changed with new id.

### LINKED ISSUE #1425: Better behavior for `Tails` animation when some component is replaced with the new one ("different one")
Currently single tail blinks for the duration of the transition

### PR DESCRIPTION
**Pull request by JBRS307**
Closes #1425 

- Merge after #1467 
- ~Snapshots smelter-labs/smelter-snapshot-tests#68~
- Snapshots smelter-labs/smelter-snapshot-tests#69
---
Additional changes:
- Changed timestamps in already existing `tiles_transitions` tests (as mentioned [here](https://github.com/software-mansion/smelter/pull/1468#discussion_r2469985442))
---
Intended behaviour:
- When tile is changed whith a new id in the spot that was previously occupied and no animation occurs it should be visible from the beginning of transition
- Otherwise it should be visible only after transition is finished
---
TODO:
- [x] Transition fix
- [x] Tests
---
Before merging:
- [x] Delete `tiles_blink` temporary example.

### CODE REVIEW

File: integration-tests/examples/tiles_blink.rs
Comment (JBRS307) [inline integration-tests/examples/tiles_blink.rs:1]: This file will be deleted before merging, I keep it for now just in case.

File: smelter-render/src/scene/tiles_component/interpolation.rs [hunk 1]
```diff
@@ -20,6 +20,10 @@ impl ContinuousValue for Vec<Option<Tile>> {
             .enumerate()
             .filter_map(|(index, tile)| tile.as_ref().map(|tile| (&tile.id, index)))
             .collect();
+        let end_id_set: HashSet<&TileId> = end
+            .iter()
+            .flat_map(|tile| tile.as_ref().map(|tile| &tile.id))
```
Comment (JBRS307) [inline smelter-render/src/scene/tiles_component/interpolation.rs]: This should be `filter_map()`

File: smelter-render/src/scene/tiles_component/interpolation.rs
Comment (JBRS307) [inline smelter-render/src/scene/tiles_component/interpolation.rs:1]: Add some comments to explain this logic.

File: smelter-render/src/scene/tiles_component/interpolation.rs [hunk 2]
```diff
@@ -36,6 +40,23 @@ impl ContinuousValue for Vec<Option<Tile>> {
...
+                        //   so tile disappears whenever any animation is triggered, for example margin change.
+                        // - Replaced tile does not exist in state represented by `end` (so no
+                        //   animation is triggered).
+                        start
+                            .iter()
+                            .flatten()
+                            .find(|start_tile| are_positions_equal(start_tile, tile))
+                            .and_then(|start_tile| match end_id_set.contains(&start_tile.id) {
+                                true => None,
+                                false => Some(ContinuousValue::interpolate(tile, tile, state)),
```
Comment (noituri) [inline smelter-render/src/scene/tiles_component/interpolation.rs]: I think the interpolation from `tile` to `tile` does nothing. Returning just a `tile` here should work

File: smelter-render/src/scene/tiles_component/interpolation.rs [hunk 3]
```diff
@@ -36,6 +40,23 @@ impl ContinuousValue for Vec<Option<Tile>> {
                             .as_ref()
                             .map(|old_tile| ContinuousValue::interpolate(old_tile, tile, state))
                     })
+                    .or_else(|| {
+                        // This handles case when a tile is swapped "in place" with entirely new tile
+                        // that has different ID.
```
Comment (wkozyra95) [inline smelter-render/src/scene/tiles_component/interpolation.rs]: What is "This" here? This sentence could be understood in 2 ways:
- This or_else is called when description is true
- This closure is changing the behavior when description is true
Neither of those interpretation is true.

File: smelter-render/src/scene/tiles_component/interpolation.rs [hunk 4]
```diff
@@ -36,6 +40,23 @@ impl ContinuousValue for Vec<Option<Tile>> {
...
+                        // It only takes effect when:
```
Comment (wkozyra95) [inline smelter-render/src/scene/tiles_component/interpolation.rs]: What is it? You technically are describing the conditions, but it only make sense if someone already knows what this code is for. I had to read the code to understand this comment.

File: smelter-render/src/scene/tiles_component/interpolation.rs [hunk 5]
```diff
@@ -36,6 +40,23 @@ impl ContinuousValue for Vec<Option<Tile>> {
...
+                        // - Exact position exists in the previous state represented by `start`
```
Comment (wkozyra95) [inline smelter-render/src/scene/tiles_component/interpolation.rs]: "Exact position exists" What does it mean that position exists?

File: smelter-render/src/scene/tiles_component/interpolation.rs [hunk 6]
```diff
@@ -52,3 +73,14 @@ impl ContinuousValue for Tile {
         }
     }
 }
+
+fn are_positions_equal(lhs: &Tile, rhs: &Tile) -> bool {
```
Comment (wkozyra95) [inline smelter-render/src/scene/tiles_component/interpolation.rs:78]: Up to you, but we already have TilePosition struct, so you could change Tail to have 2 fields (id and position) and implement Eq trait on TilePosition.

File: integration-tests/src/render_tests/tiles_transitions_tests.rs [hunk 7]
```diff
@@ -160,6 +160,124 @@ fn tiles_transitions_tests() {
...
+                "./tiles_transitions/start_with_3_inputs_all_id.scene.json"
+            )),
+            Step::RenderWithSnapshot(Duration::from_millis(0)),
+            Step::UpdateSceneJson(include_str!(
+                "./tiles_transitions/end_with_3_inputs_3_id_different_component.scene.json"
+            )),
+            Step::RenderWithSnapshot(Duration::from_millis(1)),
+            Step::RenderWithSnapshot(Duration::from_millis(150)),
+            Step::RenderWithSnapshot(Duration::from_millis(350)),
+            Step::RenderWithSnapshot(Duration::from_millis(500)),
```
Comment (wkozyra95) [inline integration-tests/src/render_tests/tiles_transitions_tests.rs:178]:
```suggestion
            Step::RenderWithSnapshot(Duration::from_millis(100)),
            Step::RenderWithSnapshot(Duration::from_millis(400)),
            Step::RenderWithSnapshot(Duration::from_millis(500)),
```
Does not really matter, but I would use timestamp like this. Eaiser to see by file name, will be sorted in PR

File: smelter-render/src/scene/tiles_component/interpolation.rs (hunk 6 above)
Comment (JBRS307) [reply smelter-render/src/scene/tiles_component/interpolation.rs:78]: I have thought about that, but implementing `PartialEq` here would not be correct as the tolerance checking makes the relation intransitive.

File: integration-tests/src/render_tests/tiles_transitions_tests.rs (hunk 7 above)
Comment (JBRS307) [reply integration-tests/src/render_tests/tiles_transitions_tests.rs:178]: If that is the case I think it would be a good idea to change that for every test (I just copied these values from existing tests).

EDIT: Did that

File: smelter-render/src/scene/tiles_component/interpolation.rs [hunk 8]
```diff
@@ -32,10 +36,25 @@ impl ContinuousValue for Vec<Option<Tile>> {
                     .get(&tile.id)
                     .and_then(|index| start.get(*index))
                     .and_then(|old_tile| {
+                        // Animation interpolation. Returns `Some(_)` only if for the tile from the `end` state
+                        // exists a tile with the same ID in the `start` state.
```
Comment (wkozyra95) [inline smelter-render/src/scene/tiles_component/interpolation.rs]:
```suggestion
                        // For each tile that existed before the last update (exists in both `start` and `end`)
                        // interpolate between those 2 states.
```

File: smelter-render/src/scene/tiles_component/interpolation.rs [hunk 9]
```diff
@@ -32,10 +36,25 @@ impl ContinuousValue for Vec<Option<Tile>> {
...
                         old_tile
                             .as_ref()
                             .map(|old_tile| ContinuousValue::interpolate(old_tile, tile, state))
                     })
+                    .or_else(|| {
+                        // This closure prevents tile from displaying empty square for the duration
+                        // of transition if the tile is swapped "in place" (i.e. no animation
+                        // occurs).
```
Comment (wkozyra95) [inline smelter-render/src/scene/tiles_component/interpolation.rs]:
```suggestion
                        // Handle a new tile (`tile` did not exist in the `start` state). Tiles that existed before
                        // last update should be handled in the previous `and_then` clousure.
                        //
                        // - If any tile existed in the same position as the new tile before the transition and still exists
                        //   somewhere in the `end` state then do not show the new tile until the end of the transition.
                        // - Otherwise, show the new tile from the start of the transition.
```

**Review by wkozyra95 — APPROVED** [review]
