### PR TITLE
[ts-sdk] Fix for `Image` component not accepting `.jpg` files

### LINKED ISSUE #1628: Jpg extension not working in `Image` component
Passing a url to an image with .jpg extension as a `source` prop on `Image` component results in an error ('Unsupported image type'). Replacing the .jpg with .jpeg in the url resolved the issue, but it's ugly, unintuitive and may not always be possible. Could you handle the .jpg extension the same way you handle the .jpeg?

### PR DESCRIPTION
**Pull request by JBRS307**
Closes #1628

### CODE REVIEW

File: ts/smelter/src/components/Image.ts [hunk 1]
```diff
@@ -63,7 +63,12 @@ function Image(props: ImageProps) {
         ? { url: props.source }
         : { serverPath: props.source };
     const extension = props.source?.split('.').pop();
-    const assetType = extension && isValidImageType(extension) ? extension : undefined;
+    const assetType =
+      extension === 'jpg'
+        ? 'jpeg'
+        : extension && isValidImageType(extension)
+          ? extension
+          : undefined;
```
Comment (noituri) [inline ts/smelter/src/components/Image.ts]: Nested ternary ifs are not really readable. I would rewrite it using normal ifs

Comment (wkozyra95) [reply ts/smelter/src/components/Image.ts]: agree, and cases like this are usually a good part to extract

but in this case I would replace this logic with using `auto` field instead

File: ts/smelter/src/components/Image.ts [hunk 2]
```diff
@@ -62,15 +61,9 @@ function Image(props: ImageProps) {
       props.source?.startsWith('http://') || props.source?.startsWith('https://')
         ? { url: props.source }
         : { serverPath: props.source };
-    const extension = props.source?.split('.').pop();
-    const assetType = extension && isValidImageType(extension) ? extension : undefined;
+    const assetType = 'auto';
```
Comment (wkozyra95) [inline ts/smelter/src/components/Image.ts]: inline that in registerImage call below
